version: 2.1

orbs:
  docker: circleci/docker@0.5.13

jobs:
  build-client:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout # pulls code from github repo
      - run:
          name: cd & update
          command: |
            cd packages
            cd client
            sudo npm install -g
      - restore_cache:
          key: dependency-cache-{{ checksum "./packages/client/package.json" }}
      - run:
          name: Build front-end
          command: |
            cd packages
            cd client
            sudo npm install
           # npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "./client/package.json" }}
          paths:
            - ./client/node_modules

  build-server:
    docker:
      - image: cimg/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys: [server-build]
      - run:
          name: Back-end build
          command: |
            cd packages
            cd server
            cd src
            node server
      - save_cache:
          paths: [server/dependencies]
          key: server-build

workflows:
  default:
    jobs:
      - build-client
      - build-server